# Set this website's info
# Change "coffeebank" to your GitHub username
# Change "moonrise" to your repository name
url: "https://lost-chronicles.pp.ua"
baseurl: "https://lost-chronicles.pp.ua"
siteIcon: /media/logo.jpeg
mineIcon: /media/iconm.ico
siteYear: 2024
siteFooterlink: 
showinSearchEngines: true
# googleAnalyticsID: (uncomment to use)


# Set basic server info
serverName: Lost Chronicles
serverDescription: A Minecraft server where we have lots of fun!
serverIP: lost-chronicles.pp.ua:54236
useBedrockForOnlineStatus: false


# Discord information
discordInvite: https://discord.gg/ZMNygWBP
discordServerID: 299881420891881473
discordChannelID: 450428756855750666


# # Navbar Links at the top of the page (uncomment "siteNav" to use)
# #   name - The title on the navbar
# #   url - The link it should go to (for example, if you have "maps.md" file, put "maps")
# #   newtab - Whether link should open in new tab
# 
siteNav:
   - name: Мапа
     url: map
     newtab: true
   - name: Скріншоти
     url: screenshots
   - name: Про Нас
     url: about


# Don't change anything below here, these are defaults set by GitHub Pages:
# ======
theme: minima
# plugins:
#   - jekyll-feed
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
